Separating debug and release by introducing seperated compiler and linker flags, and define for debug code. Removed debug symbol inclusion in executable. Added --specs=nosys.specs linker flag for release to avoid the libc undefined reference to _exit error.